sudo: required
services:
  - docker

language: python
python:
  - "2.7"
env:
    global:
      - OUT_REPO=tarantool/modules
      - GIT_REPO=https://github.com/$TRAVIS_REPO_SLUG.git
      - PROJECT=shard
    matrix:
      - OS=el DIST=6 PACK=rpm
      - OS=el DIST=7 PACK=rpm
      - OS=fedora DIST=20 PACK=rpm
      - OS=fedora DIST=21 PACK=rpm
      - OS=fedora DIST=22 PACK=rpm
      - OS=fedora DIST=23 PACK=rpm
      - OS=ubuntu DIST=trusty PACK=deb
      - OS=ubuntu DIST=precise PACK=deb
      - OS=ubuntu DIST=vivid PACK=deb
      - OS=debian DIST=jessie PACK=deb
      - OS=debian DIST=wheezy PACK=deb
      - OS=debian DIST=stretch PACK=deb
      - PACK=none

before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - gem install package_cloud

script:
  - git clone https://github.com/tarantool/build.git
  - bash build/pack/travis.sh

notifications:
  email: true
  irc: false
